### ISSUE TITLE
Instead of .txt why not support .yaml, it seems more suitable for this case

### ISSUE THREAD

**Issue by AnwarElbo** [slava-vishnyakov/laravel-migrator#2]

**Comment by slava-vishnyakov** [comment]
It's not exactly `.txt`, it's more like a DSL (domain specific language) with `.txt` extension, `YAML` (or XML, JSON, TOML, etc...) would be mu-u-u-uch longer.

For ex.: (.txt)

```
Human
  name: string Unique(index_name), Default('Alex')
  pets()

Pet
  name: string Unique(index_name2), Default('Alex')
  humans() <- Human[]
```

Equivalent YAML would be something like:

```
models:
  - name: Human
    fields:
      - name: name
        type: string
        indexes:
          - name: index_name
            type: unique
        default: Alex
    methods:
      - name: pets

  - name: Pet:
    fields:
      - name: name
        type: string
          indexes:
            - index_name2
        default: Alex
    methods:
      - name: humans
        returns: "Human[]"
```

(It can be a bit shorter, but that's about it)

Believe me, parsing YAML is way easier than creating your own DSL (this is just the tests for "reader" of this DSL https://github.com/slava-vishnyakov/laravel-migrator/blob/master/tests/ParserTest.php ), but neither YAML, nor XML, nor JSON, nor TOML was a good fit for what I was trying to do. The decision to do a DSL didn't come easy.
